export const FAQS = [
 {question:'Warum muss ich mich mit meinem Projekt bewerben?',answer:'Ich arbeite nur an ausgewählten Projekten, die ich persönlich betreuen kann. Ihre Bewerbung zeigt mir Aufgabe, Ziele und gewünschten Umfang. Sie ist unverbindlich und wird nicht automatisch zum Auftrag.'},
 {question:'Was umfasst die Basis-Homepage für 599 €?',answer:'Eine einfache Homepage auf einer Seite mit Ihren bereitgestellten Inhalten, responsiver Darstellung und Basis-SEO. Kein Kontaktformular, keine Animationen, keine individuellen Zusatzfunktionen und keine Erstellung einer Datenschutzerklärung oder anderer Rechtstexte. Erforderliche rechtliche Inhalte stellt der Auftraggeber bereit.'},
 {question:'Was unterscheidet Business und Premium?',answer:'Business bietet individuelles Design, vereinbarte Unterseiten, ein Kontaktformular und technische SEO. Premium ist ein umfassendes, individuell geplantes Projekt mit erweiterten Funktionen nach Vereinbarung. Umfang und einmaliger Preis werden im Angebot festgelegt.'},
 {question:'Sind die Preise einmalig und kommt Umsatzsteuer dazu?',answer:'Die Website-Pakete haben einen einmaligen Projektpreis. Aufgrund der Kleinunternehmerregelung wird keine Umsatzsteuer verrechnet. Domain, Hosting und zusätzlich beauftragte Betreuung sind getrennte Leistungen und werden ausdrücklich ausgewiesen.'},
 {question:'Wie funktionieren Anzahlung und Abnahme?',answer:'60 % Anzahlung sind sofort bei Auftragserteilung fällig. Die restlichen 40 % werden nach erfolgreicher Abnahme fällig. Leistungsumfang, Zeitplan und Abnahmeverfahren stehen im Vertrag.'},
 {question:'Wie viele Korrekturen sind enthalten?',answer:'Die Anzahl wird schriftlich vereinbart, maximal fünf Korrekturrunden innerhalb des abgestimmten Konzepts. Neue Funktionen oder ein komplettes Redesign sind kein Bestandteil einer normalen Korrekturrunde und werden separat beauftragt.'},
 {question:'Kann ich die Entstehung live verfolgen?',answer:'Ja. Sie erhalten eine Online-Vorschau des Entwicklungsstands. So stimmen wir Gestaltung und Inhalte früh ab, statt erst am Projektende darüber zu sprechen.'},
 {question:'Wie lange dauert die Umsetzung?',answer:'Das hängt vom vereinbarten Umfang und der Bereitstellung Ihrer Inhalte ab. Den konkreten Zeitplan halten wir vor dem Start im Vertrag fest. Eine pauschale Lieferfrist für alle Pakete gibt es nicht.'},
 {question:'Was passiert im 15-Minuten-Gespräch?',answer:'Wir besprechen Ihre Idee, Ziele, Rahmenbedingungen und Erwartungen. Das Kennenlernen ist kostenlos und unverbindlich. Anschließend entscheiden wir, ob eine Zusammenarbeit passt.'},
 {question:'Wie geht es nach dem Launch weiter?',answer:'Sie erhalten den vereinbarten Projektcode und die Übergabe. Erweiterungen und Betreuung können Sie separat beauftragen. Auch individuell entwickelte Software benötigt bei Bedarf technische Pflege und Sicherheitsupdates.'},
] as const
