import Image from 'next/image'
import { Breadcrumbs } from '@/components/layout/breadcrumbs'
import { PricingCards } from '@/components/sections/pricing-card'
import { CtaBand } from '@/components/sections/cta-band'
import { ProcessSection } from '@/components/sections/process-section'
import { SITE } from '@/lib/site'
import { pageMetadata } from '@/lib/seo-metadata'
export const metadata = pageMetadata({title:'Webdesign-Pakete | Basis 599 €, Business & Premium | ALCOR',description:'Einmalige Projektpreise: einfache Basis-Homepage für 599 €. Business und Premium nach Vereinbarung. 60 % Anzahlung, 40 % nach Abnahme. Keine Umsatzsteuer.',path:'/preise'})
export default function PreisePage(){return <><Breadcrumbs items={[{label:'Start',href:'/'},{label:'Pakete & Preise',href:'/preise'}]}/><section className="container-fluid alcor-section"><div className="alcor-section-head"><div><p className="alcor-eyebrow">Pakete & einmalige Preise</p><h1 className="alcor-page-title">Der richtige Umfang.<br /><span className="text-signal-2">Ein klarer Preis.</span></h1></div><p>Die Basis ist bewusst einfach. Business bietet mehr Gestaltung und Funktionen. Premium ist die umfassende Lösung innerhalb Ihres individuell vereinbarten Projekts.</p></div><PricingCards /></section><section className="alcor-surface"><div className="container-fluid alcor-section alcor-selection"><div className="alcor-selection-image"><Image src="/media/visual/strategy" alt="Illustration einer strukturierten Projektplanung" fill sizes="(min-width:1000px) 45vw,95vw" unoptimized/></div><div><p className="alcor-eyebrow">Verbindlicher Rahmen</p><h2>Vor dem ersten Entwurf<br />steht die Vereinbarung.</h2><p className="alcor-intro">Zwischen Ihnen und ALCOR wird ein Vertrag geschlossen. Darin stehen die abgesprochenen Leistungen, der Zeitrahmen, Mitwirkungspflichten, Abnahme und die Anzahl der Korrekturrunden.</p><ul className="alcor-contract-list"><li><strong>60 %</strong><span>Anzahlung sofort bei Auftragserteilung.</span></li><li><strong>40 %</strong><span>Restzahlung nach erfolgreicher Abnahme.</span></li><li><strong>Bis 5×</strong><span>Vereinbarte Korrekturrunden innerhalb des freigegebenen Konzepts. Kein vollständiges Redesign.</span></li></ul><p className="alcor-note">Die Live-Vorschau ermöglicht laufende Abstimmung. Ein geänderter Leistungsumfang wird vor zusätzlicher Arbeit separat vereinbart.</p></div></div></section><ProcessSection/><section className="container-fluid alcor-section alcor-legal-notes"><h2>Was zusätzlich wichtig ist.</h2><div className="alcor-notes-grid"><div><h3>Rechtliche Inhalte</h3><p>Im Basis-Paket werden keine Datenschutzerklärung und keine anderen Rechtstexte erstellt. Erforderliche Texte stellt der Auftraggeber bereit. Das bedeutet nicht, dass gesetzliche Informationspflichten entfallen. Eine rechtliche Prüfung ist keine Webdesign-Leistung.</p></div><div><h3>Hosting & Erweiterungen</h3><p>Projektpreise sind einmalig. Domain, Hosting und ausdrücklich beauftragte Betreuung sind davon getrennt. Optionales Hosting derzeit {SITE.pricing.hostingYearly} € pro Jahr; Zusatzarbeiten nach Freigabe mit {SITE.pricing.hourlyRate} € pro Stunde. Auch hierfür wird keine Umsatzsteuer verrechnet.</p></div></div></section><CtaBand/></>}
