'use client'
import {useEffect,useRef,useState} from 'react'
import Link from 'next/link'
import {usePathname} from 'next/navigation'
import {Menu,X,ArrowUpRight,Phone} from 'lucide-react'
import {SITE} from '@/lib/site'
const links=[['Leistungen','/leistungen'],['Website-Service','/website-service'],['Projekte','/referenzen'],['Pakete & Preise','/preise'],['Über mich','/ueber-mich'],['Journal','/blog'],['Kontakt','/kontakt']]
export function MobileMenu(){
 const [open,setOpen]=useState(false);const dialog=useRef<HTMLDialogElement>(null);const trigger=useRef<HTMLButtonElement>(null);const pathname=usePathname()
 useEffect(()=>{setOpen(false)},[pathname])
 useEffect(()=>{const d=dialog.current;if(!d)return;if(open){d.showModal();const previous=document.documentElement.style.overflow;document.documentElement.style.overflow='hidden';return()=>{document.documentElement.style.overflow=previous;if(d.open)d.close()}}else if(d.open){d.close();trigger.current?.focus()}},[open])
 return <div className="xl:hidden"><button ref={trigger} type="button" onClick={()=>setOpen(true)} aria-label="Navigation öffnen" aria-haspopup="dialog" aria-expanded={open} aria-controls="alcor-mobile-menu" className="inline-flex min-h-[48px] min-w-[48px] items-center justify-center text-paper"><Menu aria-hidden="true" size={27}/></button><dialog ref={dialog} id="alcor-mobile-menu" onCancel={()=>setOpen(false)} onClose={()=>setOpen(false)} aria-labelledby="alcor-menu-title" className="fixed inset-0 m-0 h-dvh max-h-none w-screen max-w-none bg-deep p-6 text-paper backdrop:bg-black/70"><div className="flex items-center justify-between border-b border-line pb-5"><p id="alcor-menu-title" className="text-xl font-semibold tracking-[0.2em]">ALCOR</p><button type="button" onClick={()=>setOpen(false)} className="inline-flex min-h-[48px] min-w-[48px] items-center justify-center" aria-label="Navigation schließen"><X size={27} aria-hidden="true"/></button></div><nav aria-label="Mobile Hauptnavigation" className="flex flex-col gap-1 py-6">{links.map(([label,href])=><Link key={href} href={href!} onClick={()=>setOpen(false)} aria-current={pathname===href?'page':(pathname.startsWith(`${href}/`)||(href==='/website-service'&&['/website-soforthilfe','/website-betreuung'].includes(pathname)))?'location':undefined} className="flex min-h-[56px] items-center justify-between border-b border-line py-3 text-xl hover:text-signal-2">{label}<ArrowUpRight size={20} aria-hidden="true"/></Link>)}</nav><div className="flex flex-col gap-4"><Link className="alcor-button" href="/bewerbung" onClick={()=>setOpen(false)}>Projekt bewerben <ArrowUpRight size={19} aria-hidden="true"/></Link><Link className="alcor-button alcor-button-outline" href="/termin" onClick={()=>setOpen(false)}>15 Minuten kennenlernen</Link><a className="alcor-text-link" href={`tel:${SITE.contact.phoneRaw}`}><Phone size={18} aria-hidden="true"/>{SITE.contact.phoneFormatted}</a></div></dialog></div>
}
