import Image from 'next/image'
import Link from 'next/link'
import { ArrowUpRight,Check } from 'lucide-react'
import type { Service } from '@/lib/services'
import { Breadcrumbs } from '@/components/layout/breadcrumbs'
import { ProcessSection } from '@/components/sections/process-section'
import { SelectedProjects } from '@/components/sections/selected-projects'
import { CtaBand } from '@/components/sections/cta-band'
const COPY={
 'website-erstellung':{kind:'design',title:'Ihre Website. Nicht irgendeine.',intro:'Ein einfacher Einstieg oder ein eigenständiger Unternehmensauftritt: Ich plane die Website passend zu Ihren Zielen und zum gemeinsam vereinbarten Umfang.',features:['Basis: einfache Homepage auf einer Seite, 599 € einmalig; kein individuelles Komplettdesign.','Basis-SEO und responsive Darstellung auch bei der einfachen Homepage.','Business: individuelles Design, vereinbarte Unterseiten und Kontaktformular.','Premium: umfassende Konzeption und erweiterte Funktionen nach Vereinbarung.','Live-Vorschau, schriftlich vereinbarter Umfang und persönliche Übergabe.'],note:'Das Basis-Paket enthält kein Kontaktformular, keine Animationen und keine Erstellung von Datenschutzerklärung oder anderen Rechtstexten. Erforderliche Inhalte stellt der Auftraggeber bereit.'},
 relaunch:{kind:'strategy',title:'Ein neuer Auftritt. Mit klarer Richtung.',intro:'Eine neue Farbe löst noch kein strukturelles Problem. Gemeinsam prüfen wir, welche Inhalte, Funktionen und Anfragewege Ihre Website tatsächlich braucht.',features:['Bestandsaufnahme von Inhalten, Seitenstruktur und technischen Voraussetzungen.','Ein abgestimmtes Konzept statt unverbindlicher Design-Experimente.','Überarbeitung der vereinbarten Seiten und Funktionen.','Berücksichtigung bestehender URLs und nötiger Weiterleitungen.','Live-Vorschau und gebündeltes Feedback innerhalb der vereinbarten Korrekturrunden.'],note:'Ein Relaunch ist ein individuell vereinbartes Projekt. Aufwand, Zeitplan und einmaliger Preis ergeben sich aus dem festgelegten Leistungsumfang.'},
 'seo-wien':{kind:'technology',title:'Verstanden werden. Gefunden werden.',intro:'Technische SEO und klare Inhalte gehören zusammen. Ich arbeite an nachvollziehbaren Grundlagen Ihrer Website — ohne garantierte Rankings oder erfundene Erfolgszahlen.',features:['Prüfung der vereinbarten Seiten auf Indexierbarkeit und technische Hindernisse.','Sinnvolle Seitentitel, Beschreibungen und Überschriftenstruktur.','Interne Verlinkung, Canonicals, Sitemap und strukturierte Daten nach Bedarf.','Abstimmung von Mobilansicht, Bildauslieferung und Ladeverhalten.','Priorisierte Maßnahmen und verständliche Dokumentation.'],note:'Suchmaschinen entscheiden selbst über Rankings. Umfangreiche laufende SEO-Betreuung und neue Inhalte werden separat vereinbart.'},
} as const
export function ServiceDetailLayout({service}:{service:Service}){const data=COPY[service.slug as keyof typeof COPY]||COPY['website-erstellung'];return <><Breadcrumbs items={[{label:'Start',href:'/'},{label:'Leistungen',href:'/leistungen'},{label:service.shortTitle,href:service.href}]}/><section className="container-fluid alcor-section alcor-selection"><div><p className="alcor-eyebrow">{service.shortTitle} · ALCOR Wien</p><h1 className="alcor-page-title">{data.title}</h1><p className="alcor-intro">{data.intro}</p><div className="alcor-actions"><Link href="/bewerbung" className="alcor-button">Projekt bewerben<ArrowUpRight size={20} aria-hidden="true"/></Link><Link href="/preise" className="alcor-button alcor-button-outline">Pakete & Preise</Link></div></div><div className="alcor-selection-image"><Image src={`/media/visual/${data.kind}`} alt={`Illustration: ${service.shortTitle}`} fill sizes="(min-width:1000px) 45vw,95vw" unoptimized priority/></div></section><section className="alcor-surface"><div className="container-fluid alcor-section"><div className="alcor-section-head"><div><p className="alcor-eyebrow">Leistung mit klarem Rahmen</p><h2>Was wir für Ihr<br/>Projekt vereinbaren.</h2></div><p>Keine unbegrenzten Pauschalversprechen: Seiten, Funktionen und Zeitplan stehen vor der Umsetzung im Vertrag.</p></div><ul className="max-w-5xl space-y-5">{data.features.map(f=><li key={f} className="flex gap-4 border-b border-line pb-5 text-lg text-paper-mute"><Check className="mt-1 shrink-0 text-signal-2" size={22} aria-hidden="true"/>{f}</li>)}</ul><p className="alcor-note mt-8 max-w-4xl">{data.note} Aufgrund der Kleinunternehmerregelung wird keine Umsatzsteuer verrechnet.</p></div></section><SelectedProjects/><ProcessSection/><CtaBand/></>}
