import type { Metadata } from 'next'
import Image from 'next/image'
import Link from 'next/link'
import { notFound } from 'next/navigation'
import { Breadcrumbs } from '@/components/layout/breadcrumbs'
import { CtaBand } from '@/components/sections/cta-band'
import { ReadingProgress } from '@/components/blog/reading-progress'
import { AuthorBox } from '@/components/blog/author-box'
import { PostCard } from '@/components/blog/post-card'
import { getAllPosts,getPostBySlug,formatPostDate,slugifyTag } from '@/lib/blog'
import { blogCover,blogCoverAlt } from '@/lib/blog-cover'
import { renderMarkdown } from '@/lib/markdown'
import { SITE } from '@/lib/site'
export const revalidate=3600
export async function generateStaticParams(){return (await getAllPosts()).map(p=>({slug:p.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const p=await getPostBySlug(slug);if(!p)return {};const image={url:`${SITE.url}${blogCover(p)}`,width:1200,height:720,alt:blogCoverAlt(p)};return {title:p.title,description:p.description||p.excerpt,alternates:{canonical:`/blog/${p.slug}`},authors:[{name:p.author}],openGraph:{type:'article',title:p.title,description:p.description||p.excerpt,url:`${SITE.url}/blog/${p.slug}`,publishedTime:p.date,modifiedTime:p.dateModified,authors:[p.author],tags:p.tags,images:[image]},twitter:{card:'summary_large_image',title:p.title,description:p.description||p.excerpt,images:[image]}}}
export default async function PostPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=await getPostBySlug(slug);if(!p)notFound();const all=await getAllPosts();const related=all.filter(x=>x.slug!==p.slug).sort((a,b)=>Number(b.tags.some(t=>p.tags.includes(t)))-Number(a.tags.some(t=>p.tags.includes(t)))).slice(0,2);const schema={'@context':'https://schema.org','@type':'BlogPosting',headline:p.title,description:p.description||p.excerpt,image:`${SITE.url}${blogCover(p)}`,datePublished:p.date,dateModified:p.dateModified||p.date,author:{'@type':'Person',name:p.author,url:`${SITE.url}/ueber-mich`},publisher:{'@type':'Organization',name:SITE.name},mainEntityOfPage:`${SITE.url}/blog/${p.slug}`,inLanguage:'de-AT'};return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,'\\u003c')}}/><ReadingProgress/><Breadcrumbs items={[{label:'Start',href:'/'},{label:'Journal',href:'/blog'},{label:p.title,href:`/blog/${p.slug}`} ]}/><article className="container-fluid alcor-section"><header className="max-w-5xl"><p className="alcor-eyebrow">{p.category} · {formatPostDate(p.date)} · {p.readingTimeMinutes} Min.</p><h1 className="alcor-page-title">{p.title}</h1><p className="alcor-intro">{p.description||p.excerpt}</p><div className="mt-6 flex flex-wrap gap-3">{p.tags.map(t=><Link key={t} href={`/blog/tag/${slugifyTag(t)}`} className="rounded border border-line px-3 py-2 text-sm text-paper-mute hover:text-signal-2">{t}</Link>)}</div></header><figure className="alcor-article-image"><Image src={blogCover(p)} alt={blogCoverAlt(p)} fill sizes="(min-width:1200px) 1100px,92vw" priority unoptimized/></figure><div className="prose-blog max-w-4xl" dangerouslySetInnerHTML={{__html:renderMarkdown(p.content)}}/><div className="max-w-4xl"><AuthorBox/></div></article>{related.length>0&&<section className="container-fluid alcor-section border-t border-line"><div className="alcor-section-head"><h2>Mehr aus dem Journal.</h2><Link href="/blog" className="alcor-text-link">Alle Beiträge →</Link></div><div className="grid gap-7 md:grid-cols-2">{related.map(x=><PostCard key={x.slug} post={x}/>)}</div></section>}<CtaBand/></>}
