import Link from 'next/link'
import { ArrowRight } from 'lucide-react'
import { Hero } from '@/components/sections/hero'
import { SelectedProjects } from '@/components/sections/selected-projects'
import { BentoGrid } from '@/components/sections/bento-grid'
import { SelectionSection } from '@/components/sections/selection-section'
import { ProcessSection } from '@/components/sections/process-section'
import { PricingCards } from '@/components/sections/pricing-card'
import { FaqSection } from '@/components/sections/faq-accordion'
import { CtaBand } from '@/components/sections/cta-band'
import { PostCard } from '@/components/blog/post-card'
import { getAllPosts } from '@/lib/blog'
import { pageMetadata } from '@/lib/seo-metadata'
export const metadata=pageMetadata({title:'Webdesign Wien für ausgewählte Projekte | ALCOR',description:'Individuelle Websites aus Wien. Persönliche Entwicklung für ausgewählte Projekte. Basis-Homepage 599 €, Business und Premium nach Vereinbarung. Projekt bewerben.',path:'/'})
export default async function HomePage(){const posts=(await getAllPosts()).slice(0,3);return <><Hero/><SelectedProjects/><BentoGrid/><SelectionSection/><CtaBand/><ProcessSection/><section className="alcor-surface"><div className="container-fluid alcor-section"><div className="alcor-section-head"><div><p className="alcor-eyebrow">Drei Ausgangspunkte</p><h2>Einfach starten.<br />Oder größer denken.</h2></div><p>599 € sind die einfache Basis-Homepage — nicht das individuelle Komplettpaket. Welcher Umfang zu Ihnen passt, klären wir persönlich.</p></div><PricingCards/></div></section>{posts.length>0&&<section className="container-fluid alcor-section"><div className="alcor-section-head"><div><p className="alcor-eyebrow">ALCOR Journal</p><h2>Gedanken für Ihren<br />nächsten Auftritt.</h2></div><Link href="/blog" className="alcor-text-link">Alle Beiträge <ArrowRight aria-hidden="true" size={20}/></Link></div><div className="alcor-journal-grid">{posts.map(p=><PostCard post={p} key={p.slug}/>)}</div></section>}<FaqSection/><CtaBand title="Ihr Projekt verdient ein persönliches Gespräch."/></>}
